include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  errors: 
    lines_longer_than_80_chars: ignore
    undefined_lint: ignore


linter:
  rules:
    - simple_directive_paths
    - unnecessary_const_in_enum_constructor
    - unnecessary_ignore
